[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[build.environment]
  REACT_APP_API_URL = "https://real-estate-agent-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
